### ISSUE TITLE
 Could not deduce instance of GEq, dependency version unspecified

### ISSUE THREAD

**Issue by banacorn** [alanz/lsp#263]
A side issue from https://github.com/alanz/lsp/pull/262

`lsp-types` doesn't build with `stack-8.6.5.yaml` and `stack-8.6.4.yaml`, but `stack-8.8.2.yaml` and `stack-8.8.1.yaml` work fine on the other hand.

I think some of the dependency version lower bound need to be specified, but I'm not sure which one it is.

```
 /Users/banacorn/haskell/lsp/lsp-types/src/Language/LSP/Types/Message.hs:620:13: error:
     • Could not deduce (GEq SMethod) arising from a use of ‘geq’
       from the context: (t1 ~ 'Notification, m1 ~~ m,
                          HasJSON (ServerMessage m), Message m ~ NotificationMessage m)
         bound by a pattern with constructor:
                    IsServerNot :: forall (m :: Method 'FromServer 'Notification).
                                   (HasJSON (ServerMessage m), Message m ~ NotificationMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:619:4-14
       or from: (t ~ 'Notification, m2 ~~ m4, HasJSON (ServerMessage m4),
                 Message m4 ~ NotificationMessage m4)
         bound by a pattern with constructor:
                    IsServerNot :: forall (m :: Method 'FromServer 'Notification).
                                   (HasJSON (ServerMessage m), Message m ~ NotificationMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:619:17-27
     • In a stmt of a 'do' block: Refl <- geq m1 m2
       In the expression:
         do Refl <- geq m1 m2
            pure HRefl
       In a case alternative:
           (IsServerNot, IsServerNot)
             -> do Refl <- geq m1 m2
                   pure HRefl
     |
 620 |     Refl <- geq m1 m2
     |             ^^^^^^^^^
```

<details><summary>here are the all 4 error messages (including the one above)</summary>

```
 /Users/banacorn/haskell/lsp/lsp-types/src/Language/LSP/Types/Message.hs:620:13: error:
     • Could not deduce (GEq SMethod) arising from a use of ‘geq’
       from the context: (t1 ~ 'Notification, m1 ~~ m,
                          HasJSON (ServerMessage m), Message m ~ NotificationMessage m)
         bound by a pattern with constructor:
                    IsServerNot :: forall (m :: Method 'FromServer 'Notification).
                                   (HasJSON (ServerMessage m), Message m ~ NotificationMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:619:4-14
       or from: (t ~ 'Notification, m2 ~~ m4, HasJSON (ServerMessage m4),
                 Message m4 ~ NotificationMessage m4)
         bound by a pattern with constructor:
                    IsServerNot :: forall (m :: Method 'FromServer 'Notification).
                                   (HasJSON (ServerMessage m), Message m ~ NotificationMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:619:17-27
     • In a stmt of a 'do' block: Refl <- geq m1 m2
       In the expression:
         do Refl <- geq m1 m2
            pure HRefl
       In a case alternative:
           (IsServerNot, IsServerNot)
             -> do Refl <- geq m1 m2
                   pure HRefl
     |
 620 |     Refl <- geq m1 m2
     |             ^^^^^^^^^

 /Users/banacorn/haskell/lsp/lsp-types/src/Language/LSP/Types/Message.hs:623:13: error:
     • Could not deduce (GEq SMethod) arising from a use of ‘geq’
       from the context: (t1 ~ 'Request, m1 ~~ m,
                          HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                          Message m ~ RequestMessage m)
         bound by a pattern with constructor:
                    IsServerReq :: forall (m :: Method 'FromServer 'Request).
                                   (HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:622:4-14
       or from: (t ~ 'Request, m2 ~~ m4, HasJSON (ServerMessage m4),
                 HasJSON (ResponseMessage m4), Message m4 ~ RequestMessage m4)
         bound by a pattern with constructor:
                    IsServerReq :: forall (m :: Method 'FromServer 'Request).
                                   (HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:622:17-27
     • In a stmt of a 'do' block: Refl <- geq m1 m2
       In the expression:
         do Refl <- geq m1 m2
            pure HRefl
       In a case alternative:
           (IsServerReq, IsServerReq)
             -> do Refl <- geq m1 m2
                   pure HRefl
     |
 623 |     Refl <- geq m1 m2
     |  
 /Users/banacorn/haskell/lsp/lsp-types/src/Language/LSP/Types/Message.hs:623:13: error:
     • Could not deduce (GEq SMethod) arising from a use of ‘geq’
       from the context: (t1 ~ 'Request, m1 ~~ m,
                          HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                          Message m ~ RequestMessage m)
         bound by a pattern with constructor:
                    IsServerReq :: forall (m :: Method 'FromServer 'Request).
                                   (HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:622:4-14
       or from: (t ~ 'Request, m2 ~~ m4, HasJSON (ServerMessage m4),
                 HasJSON (ResponseMessage m4), Message m4 ~ RequestMessage m4)
         bound by a pattern with constructor:
                    IsServerReq :: forall (m :: Method 'FromServer 'Request).
                                   (HasJSON (ServerMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ServerNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:622:17-27
     • In a stmt of a 'do' block: Refl <- geq m1 m2
       In the expression:
         do Refl <- geq m1 m2
            pure HRefl
       In a case alternative:
           (IsServerReq, IsServerReq)
             -> do Refl <- geq m1 m2
                   pure HRefl
     |
 623 |     Refl <- geq m1 m2
     |             ^^^^^^^^^

 /Users/banacorn/haskell/lsp/lsp-types/src/Language/LSP/Types/Message.hs:634:13: error:
     • Could not deduce (GEq SMethod) arising from a use of ‘geq’
       from the context: (t1 ~ 'Request, m1 ~~ m,
                          HasJSON (ClientMessage m), HasJSON (ResponseMessage m),
                          Message m ~ RequestMessage m)
         bound by a pattern with constructor:
                    IsClientReq :: forall (m :: Method 'FromClient 'Request).
                                   (HasJSON (ClientMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ClientNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:633:4-14
       or from: (t ~ 'Request, m2 ~~ m4, HasJSON (ClientMessage m4),
                 HasJSON (ResponseMessage m4), Message m4 ~ RequestMessage m4)
         bound by a pattern with constructor:
                    IsClientReq :: forall (m :: Method 'FromClient 'Request).
                                   (HasJSON (ClientMessage m), HasJSON (ResponseMessage m),
                                    Message m ~ RequestMessage m) =>
                                   ClientNotOrReq m,
                  in a case alternative
         at src/Language/LSP/Types/Message.hs:633:17-27
     • In a stmt of a 'do' block: Refl <- geq m1 m2
       In the expression:
         do Refl <- geq m1 m2
            pure HRefl
       In a case alternative:
           (IsClientReq, IsClientReq)
             -> do Refl <- geq m1 m2
                   pure HRefl
     |
 634 |     Refl <- geq m1 m2
     |             ^^^^^^^^^
```

</details>

**Comment by alanz** [comment]
I updated my cabal dependencies in a project to be

```
                     -- following needed because of https://github.com/alanz/lsp/issues/263
                     , constraints-extras == 0.3.0.2
                     , dependent-map == 0.4.0.0
                     , dependent-sum == 0.7.1.0
                     , dependent-sum-template == 0.1.0.3
```

based on https://github.com/fwcd/koka/commit/665f95928f8f898bd7713487cff51ffb3e7f8c27
and it then builds for me, using hackage at `2021-01-21T11:58:13Z`, tested with GHC 8.8.4 and 8.10.3
