### PR TITLE
Parse config from initializeOptions and pass in the old value of config to onConfigurationChange

### PR DESCRIPTION
**Pull request by wz1000**
`onConfigurationChange` is now pure, if you want to react to configuration changes you will have to define a handler for the `WorkspaceDidChangeConfiguration` message.

### CODE REVIEW

**Comment by bubba** [comment]
I thought `initializationOptions` and the workspace configuration were two different things, but it just so happened that some clients passed in the workspace configuration into it by coincidence? Which is why vscode doesn't actually pass it on startup. 
If we want to preserve compatibility with coc.vim would it be possible to make a `workspace/configuration` request immediately after initialisation in lsp like you suggested, which would then call HLS's `onConfigurationChange` handler?

**Comment by wz1000** [comment]
I'm pretty sure config was supposed to be passed into `initializationOptions` at one point, but was later supposedly deprecated. See the discussion on https://github.com/microsoft/language-server-protocol/issues/972#issue-614043677

**Review by bubba — APPROVED** [review]

**Comment by andys8** [comment]
If I'm not mistaken haskell-langauge-server 1.0.0 was released without this and should work with coc/vim. Would be awesome if this would be released and used in hls :)

**Comment by wz1000** [comment]
@andys8 we still need a lsp-test release, and I'm hoping to the all the other changes in.

/cc @bubba

**Comment by andys8** [comment]
Sounds good. Thanks for the info 👍

**Comment by bubba** [comment]
@wz1000 doing the lsp-test release now, but for some reason I can no longer build lsp-types, I'm getting some mysterious TH error. I'm not sure whats changed

```

src/Language/LSP/Types/Lens.hs:66:1: error:
    • Type constructor ‘Language.LSP.Types.Method.Method’ cannot be used here
        (perhaps you intended to use DataKinds)
    • In the kind ‘Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0’
      In the first argument of ‘Registration’, namely
        ‘(m_aaEK1 :: Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0)’
      In the first argument of ‘HasId’, namely
        ‘(Registration (m_aaEK1 :: Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0))’
   |
66 | makeFieldsNoPrefix ''Registration
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by felixonmars** [comment]
> @wz1000 doing the lsp-test release now, but for some reason I can no longer build lsp-types, I'm getting some mysterious TH error. I'm not sure whats changed
> 
> ```
> 
> src/Language/LSP/Types/Lens.hs:66:1: error:
>     • Type constructor ‘Language.LSP.Types.Method.Method’ cannot be used here
>         (perhaps you intended to use DataKinds)
>     • In the kind ‘Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0’
>       In the first argument of ‘Registration’, namely
>         ‘(m_aaEK1 :: Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0)’
>       In the first argument of ‘HasId’, namely
>         ‘(Registration (m_aaEK1 :: Language.LSP.Types.Method.Method 'Language.LSP.Types.Method.FromClient t_aaEK0))’
>    |
> 66 | makeFieldsNoPrefix ''Registration
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

I got the same failure with `lens-5`. It builds fine with `lens-4.19.2` and others unchanged.
